language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-test/protractor.conf.js --browser=firefox
deploy:
  provider: openshift
  user: dave.thompson@across.co.uk
  password:
    secure: wZm2OFG71ZvWqjVlFMO9xX/s1Xqm5yG3+bIrsqqUa+z4dhwVSgtUziQebaWF3+5UwvcvM2ztxWIufuMhRgBEdyELJgaj5oGPqyL7wei77SRQSutTjSH2l3ysm+b0yt+nIrZ0Kz1nBsEEaLFk0JJlyh/4lenIuWqGgTN8cgSRGkjOzCDURVUaTdMXhceJc6aKx0DLkHMpWPhTYQ8xPZOQVUJFrGcOWYg9MzM2+3I+sMQQLSb8HD6n72KgOFCM701mowB5BwD9ByJOMxlWKfQYTYfJwv7PN1BcIeKLU6RunnKPBxMM96WpkOLEuk4vIfMqUsHCTAEixZzT7syBexgYfGaAexbidnvy1w7kVpuD8XG/IjaDhqyFZ49je/BFtclAzOxdk+l0HEc0CzJUNrter7+uesY22lui1WhYyOLmLGKrUiDUB9prJrK8oZ8s4J7OSvjdmZUV47xb0VOZm62OI7ISM0JsM8yJHcy909BN9fn6QgG/VOetqjzFcKao+Ehm+K4TMP3ncHIxPoZ0+l8cNZNLtwZe1ySAIt7irVAqSDUdcsgk3ed+lGg4p16OhpXhsDDWElaAJI+fc6ppzOIg/q9CO7uYHsYA+iw9EEW/DXAgmKR5xr3TG7Vdaz7AU/vzrtB4hL8OT5OPwyOqZHqenw1AZc9EkuwCdGGtsCQkBZE=
  app: provisioner
  domain: handihopd
  on:
    repo: handihealth/ehrscape-provisioner
  skip_cleanup: true
