language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-test/protractor.conf.js --browser=firefox
deploy:
  provider: openshift
  user: dave.thompson@across.co.uk
  password:
    secure: zILT0F83lDMUPxlEjY6ye/aTAdSsD25tt2H6L/0/TZ4rsu3PQpEiyIl6IZfoFJXoZ99JwhsyNvurT4WmdqFi5iWY+vVoQRs2bvQjz0YF7YIgleGmK1NacMfDlv+S2cYP2XyXBSJXxOUPmQ5x5NPYgEXtpZbSfuZvFu/pmN92ViIpcqWwx8ZQYaViqlRUjV4uJFM91IjwGwu54KR9bXkYlTeBxp1IQPjc/f7eJTCnfYlXEZxVts8AEqTZFro6vge2bhbrj2/j14kianONO6hvwo1WW6A+PtN0Q8ZDiPOQyyVjySsAWZ2hG70I41Z31yZYfnuEAeIW6lyOBqPtD0Ri9IpU5QHV5iFCjnWKe7xdRv1uoFAw2ixJD6hFE3c+Rbg4NF4s4IA11n04Ootb+OhaAZF3CMA8gp8Z2p+wchg0aYJwSDCzxAfGhWPfJoqUnRAUxZAI4eTxM0Qe/aHB6IjImvRPtf/nrCcxKQZC8YLH/a/yHyrUgbjeRJQYC9F/FT6NPaQEsodMCsv/f9v/dnFlqQa/ptWVkGu03dI/MtsJclen66h41U7OhmmGIyPQM9OSpWgi9BGcog6ZIQSlkz7BzuMdfZp4dfmU3mhLmwRxccPxh+S+tHjmuJLaa9bL1+xULk+oOIHpxJfNpPXpD6kpHbTt9TdY8jMrHKkylmplN6g=
  app: provisioner
  domain: handihopd
  on:
    repo: handihealth/ehrscape-provisioner
  skip_cleanup: true
