language: node_js
node_js:
  - "0.10"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor e2e-test/protractor.conf.js --browser=firefox
deploy:
  provider: openshift
  user: dave.thompson@across.co.uk
  password:
    secure: rnMP9RhnmHWFwaBjFVuLRGc7qiQIhsRWje/uFaz0cSoSuMt6aFFxevSF7bRFCj+mp0ZnZoocxi35DkrHuwcRW+sougvDYC5NxCWS3Owe9ZB3jq8MT8vc5vNUB7SfmgkkOB2ulVuksUGA2PrQKHW7gwej1BIS2Mw68BG6nGhu4JbCCToAvnAESdydD7xkYFsAkUMM2A0SA9rKPGMvfcsWQ55ys5PPZotjjDVgWsm3xmIAiv9IG3LGNoQ1xo4Hcg7162W9wRJm3lb0Dlytf0g9E4tgH/dNPeEmBf18GzAETz3ntcCHhBQ7bWTT2sHygxK5HWazxKHMpbZUK14Vjhxe3GHSFAAJ9AuwCZ6IaQbJALxFs0g2N1NEjp/BCF6r+MVLXsew2Du8La9/cVI+hOJFYoPB8vUFFowOjL9fWsmFstcyi6ID9h4wHSG6qe7PtOeA8t6M28PnkZdvLJEfhi5xjUNP39+swTBwCra0Zm58pVqZEjBBATuz08P+a7ydsEJMAFf7YHnkPuQQAiYmBjyLRwUu3D7STS/VDVYbJJRGSDvynX0nvRI6XoWMZQEK8Tp9RaDavinjjUpjt3sufmRdaQIjWDm8OH9UUUPS/mCHFK+Rb/CH6zRSq04KtVMVTk6BL10wVetCqZ+ywdt++U/Y5nIp6v2KCoFwMHbick5j0Wg=
  app: provisioner
  domain: handihopd
  on:
    repo: handihealth/ehrscape-provisioner
  skip_cleanup: true
